#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

files_to_lint=$(git diff --cached --name-only --diff-filter=ACM | grep -E '^.+\.(js|vue)$')

if [ -n "$files_to_lint" ]; then
  npx eslint --format pretty $files_to_lint
fi